### PR TITLE
baip-0007.md

### PR DESCRIPTION
**Pull request by zhouxiaobao-2010**
BAIP: 0007
  Title: Proposal on bitASSETS reward and BTS destruction
  Authors: cn-vote  zhouxiaobao-2010
  Status: Accepted
  Type: Consensus 
  Created: 2020-06-01

[Proposal on bitASSETS reward and BTS destruction（关于BTS销毁和智能资产奖励的提案）.docx](https://github.com/bitshares/baips/files/4711178/Proposal.on.bitASSETS.reward.and.BTS.destruction.BTS.docx)
The purpose of this proposal is to establish a scientific financial model of BTS, make reasonable use of the commission income of the committee, open up resources and reduce expenditure, and promote the stable growth of BTS system value.

**bitASSETS reward**

Intelligent assets are the original assets of the system, and the corresponding holders should enjoy the dividend of system growth.
Reward amount: 20000 BTS per day
Participating assets: bitCNY, bitUSD, bitEUR, bitRUBLE
1.Reward conditions:
1)  The holding amount should exceed X. For example: those over 1000 yuan can participate in reward
2)  The holding amount needs to last for a period of time . For example, 7 days. Rewards can only be distributed if the holding amount meets 1000bitcny or above for 7 consecutive days.
2.Reward method:
1) Participating accounts should register at the beginning of each cycle.Account does not participate in reward if not registered. The registration method can be to transfer any small number of bitassets to the specified account.
3) The reward needs to be collected actively. If the reward is not collected within the time limit, this part of the reward will not be accumulated.The collection method can be to transfer any small number of bitasset to the specified account.
4) If there are too few bitassets participating in the reward plan, set the upper limit of daily yield, such as 5 ‰.
5) The more available bitassets you hold, the more rewards you get. Calculated as a minimum of 7 days. For example, if the number of bitCNY held within 7 days is 2000 3000 3000 1000 5000 5000 2000, then 1000 is the effective number. Note that the available bitassets do not include bitassets such as participating in Pending purchase\ compulsory liquidation and transfer.
6)There is a reward for recommending new registered account to participate in lock in the reward plan. If the number of locked in bitassets in the account reaches a certain amount (e.g. 100000 bitcny, other bitassets are calculated based on the exchange rate year-on-year), it can be applied as a promotion account. If the new account recommended for registration by the account participates in the locked in of smart assets, the account can obtain corresponding rewards.

**Regular destruction**

The dividend shall be destroyed at the same time as it is distributed in each reward cycle.
Destruction per week = coefficient Z * (reward per week)

**Parameter adjustment description**

For all parameters, the modification cycle is 2 weeks. Each modification can be adjusted for a function or a single parameter.
Modification conditions (one of two options):
1) Adopted by more than half of the members of the Council
2) Send a simple baip, describe the parameters you want to modify, according to the passing standard of baip.

**Continuous operation**

This proposal does not conflict with baip6(MM competition).
If baip6 passes, it will be carried out at the same time. After the consumption of the Council's stock funds, 30% of the Council's monthly income is used for destruction, 30% is used for warehouse locking and reward distribution, 30% is used for mining with hanging orders, and 10% is used for Council reservation. The parameters are adjusted in the same proportion.
If baip6 fails, the proposal will be implemented separately. After the consumption of the Council's stock funds, 30% of the Council's monthly income is used for destruction, 60% is used for lock in rewards, and 10% is used for the Council's reservation. The parameters are adjusted in the same proportion.

**organizer**

The organizer is appointed by the Council. In the early stage, a certain amount of funds will be spent by the Council account for program development, and 1% of the daily reward will be used as the organizer's salary after operation.

本提案旨在建立BTS科学的金融模式，合理运用理事会手续费收入，开源节流，促进BTS系统价值稳定增长。

**智能资产奖励计划**

智能资产为系统原生资产，相应持有者应享有系统成长的红利。奖励数量：每日2万BTS。
参与资产： bitCNY 、bitUSD 、bitEUR、bitRUBLE

奖励条件：
1）持有量需超过 X ，如超过1000bitCNY ，就可以参与奖励计划。
2）持有量需持续一段时间T，如7天，连续7天均满足1000bitCNY以上才可以获得奖励。

奖励方式：
1）参与奖励的账户每周期开始时要报名登记，如未报名登记
  则不参与奖励。报名方式可以是，向指定账号转任意小数量的bitasset。
3）奖励需要主动领取，如超时未领取，则这部分奖励不累积。 
领取方式可以是，向指定账号转任意小数量的bitasset。
4）若参加奖励的智能资产过少，则设定日收益率上限，如：5‰。
5）持有可用智能资产越多，获得奖励越多。以7天内最小值计算。如：7天内持有CNY数量为  2000，3000，3000，1000，5000，5000，5000 ，则取1000为有效数量。注意，可用智能资产不包括参加挂单、强清、转账等智能资产。
6）推荐新注册账号参与锁仓奖励计划有奖励。账户中锁仓智能资产达到某一数量（如10万bitcny，其他智能资产按照汇率同比计算）则可以申请为推广账号，若该账号推荐注册的新账号参与智能资产锁仓，则该账号可以获得相应分红。

**定期销毁**

每个奖励周期发放奖励的同时进行销毁。
每周期销毁量 = 系数z * （每周期奖励量 ）

**参数调节说明**

	对于所有参数，以2周为一次修改周期。每次修改可针对某个功能或某单个参数进行调整。
	修改条件（二选一）：
1）理事会成员半数以上通过
2）发简易的baip，描述希望修改的参数，按照baip的通过标准。 

**持续运营**

本提案与baip6(挂单挖矿)不冲突。
若baip6通过，则同时进行。待理事会存量资金消耗完毕后，每月理事会收入30％用于销毁，30％用于锁仓奖励，30％用于挂单挖矿,10％用于理事会预留。参数同比例调整。
若baip6不通过，则单独执行本提案。待理事会存量资金消耗完毕后，每月理事会收入30％用于销毁，60％用于锁仓奖励，10％用于理事会预留。参数同比例调整。

**组织者**

组织者由理事会指定。前期由理事会账户支出一定资金用于程序开发，运行后每日奖励额的1％作为组织者工资。
本提案为baip提案，若本提案连续三天超过baip阈值，则视为通过。

### CODE REVIEW

**Comment by zhouxiaobao-2010** [comment]
希望各位管理员审查

**Comment by zhouxiaobao-2010** [comment]
cn-vote 将就此提案发起投票。

**Comment by shulthz** [comment]
我想你们可以直接给BAIP-Threshold撤票，一切都可以实现。

不提issue进行讨论直接PR，你们可以的！

把花钱说成开源节流你们的话术也是了得！

I think cn-vote can remove the vote from the BAIP-Threshold, then CN-vote can do what it likes to do!

No issue to discuss, make a PR first, yes, it's so good!

**Comment by shulthz** [comment]
我想你们可以直接给BAIP-Threshold撤票，一切都可以实现。

不提issue进行讨论直接PR，你们可以的！

把花钱说成开源节流你们的话术也是了得！

这是我进入BTS社区以来，第二傻❌的提案，可见BTS社区已经沦落到什么地步！

你们的资金来自何处？怎么构成的？数据模型在哪里？如果资金来源复杂，那属于BAIP的范围吗？

I think cn-vote can remove the vote from the BAIP-Threshold, then CN-vote can do what it likes to do!

No issue to discuss, make a PR first, yes, it's so good!

**Pull request closed without merging**
